version: "3.8"

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: athena-runner
    restart: always
    privileged: true
    environment:
      NODE_ENV: production
      REDIS_HOST: athena-redis
      REDIS_PORT: 6379
      EXECUTION_QUEUE_NAME: ${EXECUTION_QUEUE_NAME}
      SUBMISSION_RESULT_QUEUE_NAME: ${SUBMISSION_RESULT_QUEUE_NAME}
      RUNNER_DB_HOST: athena-postgres-runner
      RUNNER_DB_PORT: 5432
      RUNNER_DB_USER: ${RUNNER_DB_USER}
      RUNNER_DB_PASSWORD: ${RUNNER_DB_PASSWORD}
      RUNNER_DB_NAME: ${RUNNER_DB_NAME}
    ports:
      - "${RUNNER_PORT}:3000"

    depends_on:
      - redis
      - postgres-runner
    networks:
      - athena-network

  postgres:
    image: postgres:15-alpine
    container_name: athena-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - athena-network

  postgres-runner:
    image: postgres:15-alpine
    container_name: athena-postgres-runner
    restart: always
    environment:
      POSTGRES_USER: ${RUNNER_DB_USER}
      POSTGRES_PASSWORD: ${RUNNER_DB_PASSWORD}
      POSTGRES_DB: ${RUNNER_DB_NAME}
    ports:
      - "${RUNNER_DB_PORT}:5432"
    volumes:
      - postgres_runner_data:/var/lib/postgresql/data
    networks:
      - athena-network

  redis:
    image: redis:alpine
    container_name: athena-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - athena-network

  minio:
    image: minio/minio
    container_name: athena-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    networks:
      - athena-network

networks:
  athena-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_runner_data:
  redis_data:
  minio_data:
